### ISSUE TITLE
Add the ability to pass JS2SVG options

### ISSUE THREAD

**Issue by QuentinFchx** [imagemin/imagemin-svgo#12]
Would it be possible to add the ability to pass js2svg options such as [--pretty](https://github.com/svg/svgo/blob/master/README.md#how-to-use) ?

```js
var svgo = new SVGO({
	multipass: opts.multipass || false,
	plugins: opts.plugins || [],
	js2svg: opts.js2svg || {}
});
```

**Comment by kevva** [comment]
No thanks, and `--pretty` is a useful option for a optimizer. What other options are there?

**Comment by QuentinFchx** [comment]
I did not make myself clear enough.
SVGO [already supports JS2SVG options](https://github.com/svg/svgo/blob/master/lib/svgo.js#L65) but this plugin does not allow to pass them. It's only about exposing the full SVGO api.

**Comment by kevva** [comment]
Yes, I know. But either we expose it all through just `opts` or we add individual options as we do now. What are your thoughts on this @sindresorhus?

**Comment by QuentinFchx** [comment]
`--pretty` was just an example of a js2svg option. As you said, it's better to just proxy a map of options :smile:
The code I wrote is a quick implementation of what we should add to achieve this.

**Comment by sindresorhus** [comment]
Just pass it through options. Then you don't have to document the options either, just refer to the SVGO ones.

**Comment by kevva** [comment]
The SVGO ones are so badly documented though.

**Comment by QuentinFchx** [comment]
If it's only about passing an map of options (as in the snippet of code I wrote in the issue description) I can provide a PR.
If you think about another implementation, please give me directions and I'll try my best :)
