### ISSUE TITLE
Cant process svg's with grunt contrib imagemin

### ISSUE THREAD

**Issue by Pushplaybang** [imagemin/imagemin-svgo#13]
I get the following error.  The SVG was produced with illustrator.

Warning: Error: no writecb in Transform class in file

any idea ?

**Comment by DennisBecker** [comment]
I get the same error on SVG.

**Comment by Pushplaybang** [comment]
probs should of come back to this sooner - but basically the designer who swore that "preserve illustrator editing capabilities.... blah bah.... something" option was unchecked when exporting, had left the the option checked.

yup.  that wasted hours.

**Comment by shinnn** [comment]
[I just improved error handling](https://github.com/imagemin/imagemin-svgo/commit/1f3d87dad7557130c1c87b948f2b51f427e6aa8a) and imagemin-svgo v4.2.0 emits more helpful error message in this case.

**Comment by Pushplaybang** [comment]
nice one!
