### ISSUE TITLE
Is it possible to retrieve file object within svgo call?

### ISSUE THREAD

**Issue by MikeiLL** [imagemin/imagemin-svgo#17]
Hi and thank you!

This isn't a bug so I hope you don't mind me posting here.

I would love to be able to access the `file` object so I can create a class named from the file name like so:
     
    `var path = require("path");
    var class_name = path.basename(file.relative, path.extname(file.relative));`

Based on this [readme for svgmin](https://github.com/ben-eb/gulp-svgmin/blob/master/README.md).

My gulp task looks like this, but no luck - fails without complaint.

`// ### Images
// `gulp images` - Run lossless compression on all the images.
gulp.task('images', function() {
  return gulp.src(globs.images)
    .pipe(imagemin( function ( file ) {
      var path = require("path");
      var prefix = path.basename(file.relative, path.extname(file.relative));
      return {
      progressive: true,
      interlaced: true,
      svgoPlugins: [{removeUnknownsAndDefaults: false}, {cleanupIDs: false},
        {addClassesToSVGElement: {
            className: prefix + ' svgfile',
            }}]
          };
        }
    ))
    .pipe(gulp.dest(path.dist + 'images'))
    .pipe(browserSync.stream());
});`
      
Is this possible in Imagemin?

**Comment by kevva** [comment]
This plugin only handles buffers. Use https://github.com/imagemin/imagemin if you want to do something with the filenames.

**Comment by heygrady** [comment]
https://github.com/imagemin/imagemin/blob/d4f8ddf14432cd46e414925ec740a3b0116242e3/index.js#L21

`imagemin` uses [`p-pipe`](https://www.npmjs.com/package/p-pipe) to compose all of the plugins together. The trouble here is that `p-pipe` works with only a single `input` arg.

https://github.com/sindresorhus/p-pipe/blob/2cd428fd28548976fb3d866244c2deff75a935da/index.js#L12

That means that it's not easy/possible to pass information like `sourcePath` down to the `imagemin-svgo` plugin.

Ideally, we'd be able to pass the `path` into the `info` object that `svgo` accepts.

https://github.com/svg/svgo/blob/72db8ebbbf5aa3ac82a32c5b744cb09deeba5e35/lib/svgo.js#L24

There are many places in the svgo code where it expects/supports `info.path`. Crucially, the path would be useful for svgo plugins like `prefixIds`, allowing for unique ids to be created based on the path name or by creating a hash of the source file.
