### ISSUE TITLE
svg files error in adwords

### ISSUE THREAD

**Issue by steven313** [imagemin/imagemin-svgo#18]
so i have been making banners for adwords and kept getting this error where it doesn't support sfw files so kept looking and kept looking for this file its referring to then it hit me that the svg also has some code and i found the sfw file within their (not to familiar with svg files) my question is would the svg still work if i just take out the code sfw ill past the code in down below if not what can i do the banners need to be scalable  

<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" [
	<!ENTITY ns_extend "http://ns.adobe.com/Extensibility/1.0/">
	<!ENTITY ns_ai "http://ns.adobe.com/AdobeIllustrator/10.0/">
	<!ENTITY ns_graphs "http://ns.adobe.com/Graphs/1.0/">
	<!ENTITY ns_vars "http://ns.adobe.com/Variables/1.0/">
	<!ENTITY ns_imrep "http://ns.adobe.com/ImageReplacement/1.0/">
	<!ENTITY ns_sfw "http://ns.adobe.com/SaveForWeb/1.0/">
	<!ENTITY ns_custom "http://ns.adobe.com/GenericCustomNamespace/1.0/">
	<!ENTITY ns_adobe_xpath "http://ns.adobe.com/XPath/1.0/">
]>
<svg version="1.1" id="Layer_1" xmlns:x="&ns_extend;" xmlns:i="&ns_ai;" xmlns:graph="&ns_graphs;"
	 xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="300px" height="50px"
	 viewBox="0 0 300 50" style="enable-background:new 0 0 300 50;" xml:space="preserve">
<style type="text/css">
<![CDATA[
	.st0{font-family:'Rockwell-Bold';}
	.st1{font-size:17.0079;}
	.st2{fill:#231F20;}
	.st3{font-family:'Rockwell';}
	.st4{letter-spacing:59;}
	.st5{font-size:8.5039;}
]]>
</style>
<metadata>
	<sfw  xmlns="&ns_sfw;">
		<slices></slices>
		<sliceSourceBounds  width="225.811" height="39.254" y="-42.104" x="8.876" bottomLeftOrigin="true"></sliceSourceBounds>
	</sfw>
</metadata>
<text transform="matrix(1 0 0 1 8.9106 17.1279)" class="st2 st0 st1">AT THE CONVERSE STORE</text>
<text transform="matrix(1 0 0 1 8.9102 37.4609)"><tspan x="0" y="0" class="st2 st0 st1">GATEWAY</tspan><tspan x="89.682" y="0" class="st2 st0 st1"> </tspan><tspan x="93.984" y="0" class="st2 st0 st1 st4">	</tspan><tspan x="157.685" y="0" class="st2 st0 st1">     </tspan><tspan x="179.199" y="0" class="st2 st3 st5">SHOP G275</tspan></text>
</svg>

please help ASAP 
Regards steven

**Comment by shinnn** [comment]
https://github.com/imagemin/imagemin-svgo/issues/10#issuecomment-94562229
