### ISSUE TITLE
Can't disable plugins

### ISSUE THREAD

**Issue by strarsis** [imagemin/imagemin-svgo#20]
I try to disable some plugins as described in README, but they are still used.

imagemin-svgo + imagemin are used with Gulp in this setup:
```js
[...]
.pipe(plugins.imagemin([
              imageminSvgo({
                  plugins: [
                      {removeUnknownsAndDefaults: false}
                  ]
              }))
[...]
````

**Comment by FreekVR** [comment]
The imagemin API changed in 3.0, the docs for svgo are outdated. You need to do:

`[...]
        .pipe(imagemin([
                imagemin.svgo({plugins: [{removeUnknownsAndDefaults: false}]}),
            ]
        ))`

Note that this will ONLY run svgo, you will need to pass other plugins you want to run in the same array as 'imagemin.svgo'

**Comment by strarsis** [comment]
And another reason was that layzpipe expects the arguments to be used for the plugin passed as second argument to its pipe(...) method - however, this doesn't apply to the image plugins inside imagemin option array, their constructor/setup methods have to be invoked as usual.
```js
[...]
return lazypipe()
    .pipe(plugins.imagemin, [
              plugins.imagemin.svgo({
                  plugins: [
                      {removeUnknownsAndDefaults: false}
                  ]
              })
   ]);
[...]
````
