### ISSUE TITLE
Incorrectly escapes '&', bungled input/output

### ISSUE THREAD

**Issue by strarsis** [imagemin/imagemin-svgo#21]
This imagemin plugin entitiy-escapes `&` characters with `&amp;` 
although `&` is also used for other entities like `&apos;`.

This results in changed SVG input which results in 
incorrect svgo output, e.g. `&apos;` becomes `&amp;apos;`.

Offending line: https://github.com/imagemin/imagemin-svgo/blob/master/index.js#L25
What would be the purpose of this string replacement anyway?

Running svgo directly results in correct output.

Edit: PR: https://github.com/imagemin/imagemin-svgo/pull/22

**Comment by Tallkotten** [comment]
I also have this problem. You either have to remake your SVG so that it doesn't use fonts or else this packet is totally useless

**Comment by sindresorhus** [comment]
Fixed by https://github.com/imagemin/imagemin-svgo/commit/47cdb503fb73c981db76171ec30b88dc9cf503c2.
