### ISSUE TITLE
add option to disable is-svg check

### ISSUE THREAD

**Issue by mdreizin** [imagemin/imagemin-svgo#23]
In a lot of cases [`is-svg`](https://github.com/sindresorhus/is-svg) returns incorrect results for valid `svg`.

I would be nice to have ability to pass `svg: true` or other flag to avoid the following check:

```js
if (!isSvg(buf)) {
    return Promise.resolve(buf);
}
```

**Comment by shinnn** [comment]
This problem can be more properly fixed by improving `is-svg` package. `svg` option is not a fundamental solution.

> In a lot of cases [`is-svg`](https://github.com/sindresorhus/is-svg) returns incorrect results for valid `svg`.

Open a new issue about this on https://github.com/sindresorhus/is-svg/issues.
