### ISSUE TITLE
Options dont work

### ISSUE THREAD

**Issue by majabee** [imagemin/imagemin-svgo#24]
gulp: 3.9.1
imagemin-svgo: 5.2.0

I'm using imagemin-svgo in my gulp project. Here´s my gulpfile:
```
var imagesTask = function() {
  return gulp.src([paths.src, exclude])
    .pipe(changed(paths.dest))
    .pipe(imagemin({
      use: [
        svgo({
            plugins: [
                {removeXMLProcInst : false}
            ]
        })]}))
    .pipe(gulp.dest(paths.dest))
}

```
In my original svg I have a XML processing instruction which I need.
After I run the imagemin task that  XML processing instruction is gone even though I do set the option to false. What am I doing wrong or is this perhaps a bug?

**Comment by majabee** [comment]
Just as a comment I tried it with removeXMLProcInst : true too just to check if anything changed but it's always removed.

**Comment by kevva** [comment]
We're just pushing the options to SVGO. If it doesn't work it's something with their module. Open an issue at https://github.com/svg/svgo/issues/new if the problem persist.
