### ISSUE TITLE
Breaks some of the earlier optimised images.

### ISSUE THREAD

**Issue by nashokin** [imagemin/imagemin-svgo#28]
Some of the images optimised before are broken after running this plugin on them. Files before and after are attached.
[Archive.zip](https://github.com/imagemin/imagemin-svgo/files/988698/Archive.zip)

**Comment by Markovnin** [comment]
@nashokin I have the same issue with one of my files. Did you manage to fix it?

**Comment by kevva** [comment]
This is an issue with [svgo](https://github.com/svg/svgo) as far as I can tell. Open an issue over there.

**Comment by nashokin** [comment]
https://github.com/svg/svgo/issues/745

**Comment by nashokin** [comment]
Still breaks. Logged an issue with svgo and have been referred back. (https://github.com/svg/svgo/issues/745)

These are the debug files, it add a closing tag at the end, which breaks it.
[svgo.zip](https://github.com/imagemin/imagemin-svgo/files/1146964/svgo.zip)

This is the automation file, line 138-180. The code itself is pretty basic.
[build-campaigns.js.zip](https://github.com/imagemin/imagemin-svgo/files/1146966/build-campaigns.js.zip)

Any help with this is appreciated, thanks.

**Comment by JoshyPHP** [comment]
If you want to improve your chances you should provide a way to reproduce the issue with a single line of code, not a 12 KB script.

**Comment by nashokin** [comment]
Np.
`imagemin([srcPath + file + '/*.svg'], assetsPath + file, {use: [imageminSvgo({plugins: [{removeViewBox: false}]})]}).then(() => { console.log('Svg images optimized'); });`
