### ISSUE TITLE
What are the breaking changes from 5.x to 6.x?

### ISSUE THREAD

**Issue by adamreisnz** [imagemin/imagemin-svgo#31]
Can't find any information about it in the readme or release notes. Any breaking changes?

**Comment by sindresorhus** [comment]
The SVGO version was bumped: https://github.com/imagemin/imagemin-svgo/commit/2af0dbe575a6ea3905b87f83cab2b4cdad567f13

SVGO release notes: https://github.com/svg/svgo/releases
