### ISSUE TITLE
Update svgo dependency to 1.2.2 to fix js-yaml vulnerability

### ISSUE THREAD

**Issue by remidenele** [imagemin/imagemin-svgo#37]
[svgo 1.2.2](https://github.com/svg/svgo/issues/1099) fixes the [js-yaml < 3.13.1 vulnerability](https://www.npmjs.com/advisories/813).

Can you update svgo from 1.0.5 to 1.2.2 in package.json?

**Comment by tyrann0us** [comment]
As of February 19 2020, the latest SVGO version is 1.3.2, see https://github.com/svg/svgo/releases. @bensampaio, can you refresh your PR (#38)?

@sindresorhus, @kevva, it would be great if you could take care of request. Thanks!
