### ISSUE TITLE
is-svg 4.2.1 ReDoS vulnerability reported

### ISSUE THREAD

**Issue by shornuk** [imagemin/imagemin-svgo#45]
Hi, 

Github is reporting a ReDoS vulnerability with `is-svg v4.2.1`. Looks like it needs to be bumped up to `v4.2.2` or later.

https://github.com/advisories/GHSA-7r28-3m3f-r2pr

**Comment by 1000ch** [comment]
Fixed on [`v10.0.0`](https://github.com/imagemin/imagemin-svgo/releases/tag/v10.0.0), thank you for your report.
